data: 
  class: data.two_moons.TwoMoonsDataModule
  params:
    n_samples: 1000
    noise: 0.1
    batch_size: 32

model: 
  class: models.nflows.SimpleFlow
  params:
    input_dim: 2
    hidden_dim: 64
    num_layers: 4